name: afaci-caddy

networks:
  afaci-network:
    external: true
    name: afaci_afaci-network

volumes:
  caddy-data:
  caddy-config:

services:
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
    networks:
      - afaci-network
