name: ci-prod

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  ruff-sca:
    name: ruff
    runs-on: afaci-runner-01
    steps:
      - name: Checkout code by ruff
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Run Ruff (Linting)
        run: ruff check .

      - name: Run Ruff (Format Check)
        run: ruff format --check .


  build:
    name: build
    runs-on: afaci-runner-01
    needs:
      - ruff-sca
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Extract Tag Name
        id: vars
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - run: docker build -f Dockerfile.prod -t afaci-ai-backend:${{ env.TAG_NAME }} -t afaci-ai-backend:prod .


  deploy:
    runs-on: afaci-runner-01
    needs: build
    steps:
      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          envs: APP_PATH,GH_PAT
          script: |
            cd $APP_PATH
            git -c http.extraheader="AUTHORIZATION: basic $(echo -n "x-access-token:$GH_PAT" | base64)" fetch --tags
            git fetch --tags
            git checkout tags/${{ github.ref_name }}
            docker compose -f docker-compose.prod.yml up --build -d
        env:
          APP_PATH: ${{ vars.APP_PATH }}
          GH_PAT: ${{ secrets.GH_PAT }}


  create-release:
    name: Create GitHub Release
    runs-on: afaci-runner-01
    needs: deploy
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
