name: test-runner
on: workflow_dispatch

jobs:
  smoke:
    runs-on: [afafci-runner-01, ARM64]
    steps:
      - run: docker run --rm alpine echo ok
      - run: git --version
      - run: echo "script ok" > script.sh && bash script.sh
